language: node_js
node_js:
  - "10"
cache:
  yarn: true
install:
  - yarn
script:
  - yarn workspace ganymede test
  - yarn workspace vim build
  - yarn workspace iterm build
  - yarn workspace ganymede-vscode-theme build
  - yarn workspace next build
